ADMIN_USER: admin
ADMIN_PASSWORD: 1234
ALGOLIASEARCH_APPLICATION_ID: UJ5WYC0L7X
ALGOLIASEARCH_API_KEY: YourAPIKey
ALGOLIASEARCH_API_KEY_RO: 08240194d5ef567a9f14e0f066bace0c
AMAZON_ACCESS_KEY_ID: s3accesskeyid
AMAZON_SECRET_ACCESS_KEY: s3secretaccesskey
RATE_LIMIT_WHITE_LIST:
  - 127.0.0.1
HN_API_URL: https://hacker-news.firebaseio.com
SECRET_TOKEN: 7c595a8c9befb8205d9cefc9ccbe7827fa8d48e2b75ed497cfc61b7940fef908c255ff087498dc176e952211cf896dd3ff2f5b88a9da65da83cc7a2f57c1b45d
